# Generated by Django 3.1.3 on 2020-11-23 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 23, 10, 36, 25, 507425, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorties',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
