# Generated by Django 3.1.3 on 2020-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201123_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorties',
            name='alias',
            field=models.URLField(max_length=300),
        ),
    ]
