# Generated by Django 3.1.3 on 2020-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201127_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorties',
            name='alias',
            field=models.CharField(default='lzexr', max_length=5, unique=True),
        ),
    ]
