# Generated by Django 3.1.3 on 2020-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201127_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorties',
            name='alias',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
