apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shorty.fullname" . }}
  labels:
    {{- include "shorty.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "shorty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "shorty.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shorty.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SHORTY_PG_DB
            value: {{ .Values.env.SHORTYPGDB | quote }}
          - name: SHORTY_PG_USERNAME
            value: {{ .Values.env.SHORTYPGUSERNAME | quote }}
          - name: SHORTY_PG_PASSWORD
            value: {{ .Values.env.SHORTYPGPASSWORD | quote }}
          - name: SHORTY_PG_HOST
            value: {{ .Values.env.SHORTYPGHOST | quote }}
          - name: SHORTY_PG_PORT
            value: {{ .Values.env.SHORTYPGPORT | quote }}
          - name: DJANGO_SECRET_KEY
            value: {{ .Values.env.DJANGOSECRETKEY | quote }}
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
