apiVersion: v1
kind: Service
metadata:
  name: {{ include "shorty.fullname" . }}
  labels:
    {{- include "shorty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "shorty.selectorLabels" . | nindent 4 }}
